Repository Cocktail-Masters/Banana-Vote-FE, pull requests merged in 2023-04, with the labels that each got.

#82 스토어 UI 구현
  src/app/[lng]/store/layout.tsx
  src/app/[lng]/store/page.tsx
  src/assets/images/default_item.png
  src/components/common/PageTitle.tsx
  src/components/feed/FeedListArea.tsx
  src/components/store/CategoryArea.tsx
  src/components/store/CategoryItem.tsx
  src/components/store/FilterArea.tsx
  src/components/store/Goods.tsx
  src/components/store/GoodsList.tsx
  src/components/store/GoodsListArea.tsx
  src/components/store/StoreSection.tsx
  src/components/store/__test__/DummyData.ts
  src/constants/store.ts
  src/hooks/reactQuery/useStoreGoodsQuery.ts
  src/types/index.d.ts
Labels: feat

#91 Pretendard Font 적용
  public/fonts/Pretendard-Black.woff2
  public/fonts/Pretendard-Bold.woff2
  public/fonts/Pretendard-ExtraBold.woff2
  public/fonts/Pretendard-ExtraLight.woff2
  public/fonts/Pretendard-Light.woff2
  public/fonts/Pretendard-Medium.woff2
  public/fonts/Pretendard-Regular.woff2
  public/fonts/Pretendard-SemiBold.woff2
  public/fonts/Pretendard-Thin.woff2
  src/app/[lng]/globals.css
  src/app/[lng]/layout.tsx
  tailwind.config.js
Labels: chore

#128 tailwind config 다크모드 색상 규격 설정
  tailwind.config.js
Labels: documentation

#140 다크모드화 (메인, 스토어)
  src/app/[lng]/page.tsx
  src/components/animation/ThreeDotsMenuButton.tsx
  src/components/animation/VoteIcon.tsx
  src/components/common/cardList/Card.tsx
  src/components/common/cardList/CardDescription.tsx
  src/components/common/cardList/CardImage.tsx
  src/components/common/menu/OptionMenu.tsx
  src/components/feed/Feed.tsx
  src/components/feed/FeedHeader.tsx
  src/components/feed/FeedListArea.tsx
  src/components/feed/FeedTitle.tsx
  src/components/feed/VS.tsx
  src/components/feed/VoteItem.tsx
  src/components/feed/VoteItemList.tsx
  src/components/home/RankingBox.tsx
  src/components/home/RankingListArea.tsx
  src/components/home/RecommendArea.tsx
  src/components/home/VoteCreateBar.tsx
  src/components/home/VoteSearchBar.tsx
  src/components/store/CategoryArea.tsx
  src/components/store/FilterArea.tsx
  src/components/store/Goods.tsx
  src/components/store/StoreSection.tsx
Labels: feat

#143 국제화 (메인, 스토어)
  language/en.json
  language/jp.json
  language/ko.json
  src/app/[lng]/store/page.tsx
  src/components/feed/Feed.tsx
  src/components/feed/FeedHeader.tsx
  src/components/feed/FeedListArea.tsx
  src/components/feed/FeedTitle.tsx
  src/components/feed/VoteItem.tsx
  src/components/feed/VoteItemList.tsx
  src/components/home/RankingBox.tsx
  src/components/home/RankingListArea.tsx
  src/components/home/RecommendArea.tsx
  src/components/home/RecommendBox.tsx
  src/components/home/VoteCreateBar.tsx
  src/components/home/VoteSearchBar.tsx
  src/components/store/StoreSection.tsx
Labels: feat

#149 Feature/145
  language/en.json
  language/jp.json
  language/ko.json
  src/app/[lng]/event/@modal/(..)(..)vote/[detail]/page.tsx
  src/app/[lng]/event/@modal/(..)vote/[detail]/page.tsx
  src/components/common/modal/Description.tsx
  src/components/common/modal/Header.tsx
  src/components/common/modal/index.tsx
  src/components/declaration/index.tsx
  src/components/event/ContentList.tsx
  src/components/modal/Modal.tsx
  src/components/modal/Portal.tsx
  src/components/vote/detail/Item.tsx
  src/components/vote/detail/ItemCard.tsx
Labels: feat

#153 트렌딩 태그 표시 기능 추가, 검색 안내 문구 추가
  language/en.json
  language/jp.json
  language/ko.json
  src/app/[lng]/home/hydratedHome.tsx
  src/app/[lng]/home/page.tsx
  src/app/api/home/tag/route.ts
  src/components/common/tag/Tag.tsx
  src/components/common/tag/TagList.tsx
  src/components/feed/Feed.tsx
  src/components/feed/FeedListArea.tsx
  src/components/feed/VS.tsx
  src/components/feed/VoteItem.tsx
  src/components/feed/VoteItemList.tsx
  src/components/feed/__test__/useFeedListDummy.ts
  src/components/home/TagBox.tsx
  src/components/home/TagListArea.tsx
  src/components/home/VoteSearchBar.tsx
  src/components/home/__test__/tagTop10Dummy.ts
  src/hooks/reactQuery/useTagTop10Query.ts
  src/hooks/useSearchVoteByKeyword.ts
  src/types/index.d.ts
Labels: feat

#160 zustand store 생성, user slice 생성, 서버사이드 렌더링으로 인한 hydration 이슈 해결
  package.json
  src/components/feed/Test.tsx
  src/hooks/useStore.ts
  src/store/index.ts
  src/store/slices/user.ts
  src/types/index.d.ts
  yarn.lock
Labels: feat

#164 피드 voteitem 클릭 시 이미지 모달 띄우기
  src/app/[lng]/home/hydratedHome.tsx
  src/components/common/tag/TagList.tsx
  src/components/feed/Feed.tsx
  src/components/feed/FeedListArea.tsx
  src/components/feed/ImageModal.tsx
  src/components/feed/VoteItem.tsx
  src/components/feed/VoteItemList.tsx
  src/components/feed/__test__/useFeedListDummy.ts
  src/components/home/VoteSearchBar.tsx
  src/hooks/reactQuery/useFeedListQuery.ts
  src/hooks/useSearchVoteByKeyword.ts
  tailwind.config.js
Labels: feat

#171 Axios instance 생성, 요청 테스트 완료
  src/app/[lng]/layout.tsx
  src/common/axiosInstance.ts
  src/components/home/RankingBox.tsx
  src/components/home/RankingListArea.tsx
  src/hooks/reactQuery/useRankingTop5Query.ts
Labels: feat
